name: Build cnping

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Build-for-Linux:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
           debhelper-compat \
           libglvnd-dev \
           libx11-dev \
           libxext-dev \
           libxinerama-dev \
           mesa-common-dev \
           make \
           build-essential \
           binutils-mingw-w64-i686 \
           gcc-mingw-w64-i686 \
           g++-mingw-w64-i686 \
           devscripts \
           appstream \
           imagemagick \
           desktop-file-utils

    - name: Build
      run: make cnping cnping.exe
        
    - uses: actions/upload-artifact@v4
      with:
        name: cnping-exe
        path: "*.exe"

    - uses: actions/upload-artifact@v4
      with:
        name: cnping-icon
        path: "cnping.ico"

    - name: Build deb
      run: debuild --no-sign
      
    - uses: actions/upload-artifact@v4
      with:
        name: cnping-debian
        path: |
          /home/runner/work/cnping/*.deb
          /home/runner/work/cnping/*.ddeb
          
    - name: Validate AppStream data
      run: appstreamcli validate freedesktop/com.github.cntools.cnping.metainfo.xml
    - name: Validate desktop file
      run: desktop-file-validate freedesktop/com.github.cntools.cnping.desktop
      
#  Build-RPM-for-Fedora:
#    runs-on: ubuntu-latest
#    container: dreua/ ...
#    steps:
#    - name: RPM Build
#      run: /cnping/cnping-build
#    - uses: actions/upload-artifact@v4
#      with:
#        name: cnping-fedora-rpm
#        path: /github/home/rpmbuild/**/*.rpm
